### ISSUE TITLE
Theme seems to stop Pigment color highlights from working properly

### ISSUE THREAD

**Issue by wahidrahim** [burodepeper/minimal-syntax-dark#1]
<img width="363" alt="screen shot 2016-10-07 at 3 47 16 pm" src="https://cloud.githubusercontent.com/assets/7417976/19203472/5adf223e-8ca5-11e6-97da-784ba7adfcba.png">

As shown above. Colors don't seem to be highlighting. Everything is updated.

**Comment by burodepeper** [comment]
Could you post a list of the packages you have installed? I think there's something going wrong in combination with another package, probably one that enhances CSS with color variable previews.

**Comment by burodepeper** [comment]
Oh, wait, I only just now read the title of the issue ; ) My bad. Yeah, `pigments`, couldn't remember the name. I'll have a quick look to see if there's an easy fix on my end.

**Comment by burodepeper** [comment]
If you switch the "Marker Type" setting in `pigments` to `background`, it works as intended. You probably have it set to `native-background` now. A quick search hasn't revealed any specifics about what `native-background` does, except that the package has switched to using it as default. I suggest switching to the regular `background` and everything should be fine again.

**Comment by burodepeper** [comment]
![schermafbeelding 2016-10-10 om 19 05 23](https://cloud.githubusercontent.com/assets/3703530/19244607/62b6368a-8f1d-11e6-997c-becd809ec836.png)

**Comment by wahidrahim** [comment]
Yeah, that works. Using `background` now.

Thanks!
